PARAMETER M IS TRUE.
RUN ONCE LIB.
for n in ALLNODES {remove n.}
FUNCTION V2MI {PARAMETER T. LOCAL P IS POSITIONAT(SHIP,UT(T))-BODY:position. LOCAL O IS OrbN(TARGET). LOCAL CV IS VELOCITYAT(SHIP,UT(T)):ORBIT. RETURN CV:MAG*(ANGLEAXIS(90-VANG(CV,P),O)*VCRS(P,O)):NORMALIZED - CV.}
LOCAL A IS  ETA_AN(ORbN(TARGET)). LOCAL D IS ETA_DN(ORbN(TARGET)).
IF M {LOCAL VA IS V2MI(A). LOCAL VD IS V2MI(D). IF VA:MAG < VD:MAG VNODE(VA,A). ELSE VNODE(VD,D).}
ELSE VNODE(V2MI(MIN(A,D)),MIN(A,D)).